TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devhumiditycell.db
DB += devhumiditycell.proto

#=======================================
include $(TOP)/configure/RULES
